{
    "name": "RingCentral Integration",
    "version": "19.0.2.1.0",
    "category": "Phone",
    "summary": "RingCentral call logging, recordings, transcripts and sentiment-based ticketing",
    "author": "Corvex Consult",
    "license": "LGPL-3",
    "depends": [
        "base",
        "contacts",
        "mail",
        "helpdesk",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/rc_data.xml",
        "data/rc_helpdesk_tags.xml",
        "data/rc_mail_template.xml",
        "views/rc_call_log_views.xml",
        "views/rc_config_views.xml",
        "views/rc_sentiment_provider_views.xml",
        "views/res_partner_views.xml",
        "views/helpdesk_ticket_views.xml",
        "views/rc_wizard_views.xml",
    ],
    "installable": True,
    "application": True,
}
